# Meta-train
python ag_news.py
python amazon_massive_scenario.py
python amazon_counterfactual_en.py
python app_reviews.py
python beaver_tails.py
python boolq.py
puthon brag_action.py
python circa.py
python clickbait.py
python climate_commitments_actions.py
python climate_fever.py
python climate_sentiment.py
python cola.py
python copa.py
python covid_fake_news.py
python dbpedia_14.py
python disaster_response_message.py
python emo.py
python emotion.py
python environmental_claims.py
python ethos.py
python fever.py
python financial_phrasebank.py
python function_of_decision_section.py
python hate_speech18.py
python health_fact.py
python i2d2.py
python imdb.py
python insincere_questions.py
python is_humor.py
python jailbreak_classification.py
python lexical_rc_cogalexv.py
python lexical_rc_root09.py
python liar.py
python limit.py
python logical_fallacy_detection.py
python metaphor_boolean.py
python mrpc.py
python news_data.py
python poem_sentiment.py
python pragmeval_emergent.py
python pragmeval_sarcasm.py
python pragmeval_verifiability.py
python prosocial_dialog.py
python pun_detection.py
python qqp.py
python rotten_tomatoes.py
python semeval_absa_laptop.py
python semeval_absa_restaurant.py
python senteval_cr.py
python senteval_subj.py
python silicone_dyda_da.py
python sms_spam.py
python sst2.py
python sst5.py
python student_question_categories.py
python tcfd_recommendations.py
python this_is_not_a_dataset.py
python toxic_conversations.py
python trec.py
python wiki_hades.py
python wiki_qa.py
python wsc.py
python yahoo_answers_topics.py


## Meta-test NLI
python rte.py
python acl_arc.py
python babi_nli.py
python cb.py
python wic.py
python vitaminc.py
python qnli.py
python wnli.py
python sick.py
python mnli.py
python rct20k.py
python medical_question_pairs.py
python scierc.py
python sara_entailment.py
python stance_abortion.py
python stance_feminist.py
